---
title: "Untitled"
output: html_document
date: '2023-06-16'
---


# Using R to identify author clusters

```{r}
library(igraph)
g <- make_full_graph(5) %du% make_full_graph(5) %du% make_full_graph(5)
g <- add_edges(g, c(1, 6, 1, 11, 6, 11))
plot(g)

wtc <- cluster_walktrap(g)
modularity(wtc)
modularity(g, membership(wtc))

plot(wtc, g)

wtc <- cluster_louvain(g, weights = NULL, resolution = 1)
plot(wtc, g)

communities(wtc)

# read .gephi format # https://gvegayon.github.io/rgexf/
library(rgexf)
g <- system.file("C:/Users/86188/Dropbox/Coauthor_papers/pcc_correlation/es_conversion/A-Chen.gephi", package="rgexf")
g <- read.gexf(g)

net <- read.gexf("C:/Users/86188/Dropbox/Coauthor_papers/pcc_correlation/es_conversion/A-Chen.gephi")

read.graph("A-Chen.gephi", format = "graphml")

```



https://ardata-fr.github.io/flextable-book/default-settings.html
https://stackoverflow.com/questions/70139600/export-flextable-to-word-in-r
```{r}
library(metafor)
library(flextable)

# Load data
data(dat.bcg)
dat.bcg$alloc <- as.factor(dat.bcg$alloc)

# mixed-effects model with alloc as a moderator
res <- rma(ai=tpos, bi=tneg, ci=cpos, di=cneg, 
           mods= ~ I(alloc) - 1, measure="RR", data=dat.bcg, method="DL", test = "t")

# Extract model estimates
estimates <- data.frame(
  Coefficient = c("Intercept", "Slope"),
  Estimate = res$beta[1],
  `95% CI` = res$ci.lb[1],
  `p-value` = format.pval(res$pval, eps = 0.001, digits = 2)[1],
  stringsAsFactors = FALSE
)

mod = res

mod_table <- function(mod){
  beta <- data.frame(round(mod$b,3),row.names = row.names(mod$b))
  CI <- data.frame(sprintf("[%0.3f, %0.3f]", mod$ci.lb, mod$ci.ub))
  t <- data.frame(mod$zval)
  df <- cbind(beta,CI,t)
  names(df) <- c("Estimate","95% CI","t")
  return(df)
  #return(db.mf[,c("estimate","mean","lower","upper")])
  
}

ft <- mod_table(res)
ft <- tibble::rownames_to_column(ft, "Coefficient")


ft %>% flextable() %>% 
   mk_par(j = 2, part = "header", value = as_paragraph(as_i("β"), as_sub("0"))) %>%
   mk_par(j = 4, part = "header", value = as_paragraph(as_i("t"), as_sub(res$QMdf[2]))) %>% 
   colformat_double(j = 4, digits = 3) %>%
  autofit()


# formula example - https://www.ardata.fr/en/flextable-gallery/2021-05-05-columns-names-with-mathjax/

ft <- data.frame(
  `\\beta_0` = rep(-1, 4),
  `\\beta_1` = rep(1, 4),
  `X_i` = c(2, 1, 0, -1),
  `p` = runif(4), check.names = FALSE) %>% 
  flextable()  %>% 
  mk_par(i = 1, part = "header",
         value = flextable::as_paragraph(
           flextable::as_equation(.,width = .1, height = .2)),
         use_dot = TRUE) |> 
  autofit()


estimates.CI <- function(model){
  db.mf <- data.frame(round(model$b,3),row.names = 1:nrow(model$b))
  db.mf <- cbind(db.mf,round(model$ci.lb,3),round(model$ci.ub,3),row.names(model$b))
  names(db.mf) <- c("mean","lower","upper","estimate")
  return(db.mf[,c("estimate","mean","lower","upper")])
}


# Create table using flextable
tbl <- flextable(estimates) %>%
  set_caption("Meta-Regression Model Estimates") %>%
  align(align = "center", part = "all") %>%
  autofit()

# Save table to a file
save_as_docx("my table 1" = tbl, "my table 2" = tbl, path ="meta-regression-estimates.docx") # https://ardata-fr.github.io/flextable-book/rendering.html

print(tbl, preview = "docx")

as_flextable(res)


# example
ft <- flextable(airquality[sample.int(10),])
ft <- add_header_row(ft,
  colwidths = c(2, 2,2),
  values = c("Air quality", "Time","A")
)

ft <- theme_vanilla(ft)


flextable(
  data = head(airquality), 
  col_keys = c("Ozone", "Solar.R", "col1", "Month", "Day")) %>%  
  width(j = "col1", width = .5) %>% 
  empty_blanks()


# data prep ----
z <- data.table::as.data.table(ggplot2::diamonds)
z <- z[, list(
  price = mean(price, na.rm = TRUE),
  list_col = list(.SD$x)
), by = "cut"]

# flextable ----
ft <- flextable(data = z) %>%
  mk_par(j = "list_col", value = as_paragraph(
    plot_chunk(value = list_col, type = "dens", col = "#ec11c2", 
               width = 1.5, height = .4, free_scale = TRUE)
  )) %>%
  colformat_double(big.mark = " ", suffix = " $") %>% 
  set_header_labels(box = "composite content", density = "density") %>% 
  autofit()
ft

# 95% confidence intervals
# create a data frame with the confidence interval
conf_int <- data.frame(lower = 0.75, upper = 0.85)

# format the confidence interval as a string
conf_int_str <- sprintf("[%0.2f, %0.2f]", conf_int$lower, conf_int$upper)

# create a flextable and insert the confidence interval
ft <- flextable(data.frame(value = 0.8, conf_interval = conf_int_str))

```
